FROM nginx:1.27-alpine
ENV MEDIA_IMAGE_SOURCES=https:

RUN sed -i '/^user /d' /etc/nginx/nginx.conf \
    && rm -f /etc/nginx/conf.d/default.conf \
    && touch /var/run/nginx.pid \
    && chown nginx:nginx /var/run/nginx.pid \
    && chown -R nginx:nginx /var/cache/nginx /etc/nginx/conf.d
COPY --chown=nginx:nginx infra/gateway/nginx.conf.template /etc/nginx/templates/default.conf.template
USER nginx
EXPOSE 8088
