fn public_page_fixtures() -> Vec<ContentFixture> {
    let mut pages = vec![
        public_page_fixture(
            0x100,
            "development/content/products-index/en",
            "home",
            "products-index",
            "Products Development Preview",
            "/en/products",
            "productIndex",
            "Products",
            "Browse normalized product categories; models appear only after validated Product Master publication.",
        ),
        public_page_fixture(
            0x101,
            "development/content/products-centrifugal/en",
            "home",
            "products-centrifugal",
            "Centrifugal Development Preview",
            "/en/products/centrifugal",
            "productFamily",
            "Product category",
            "Development category presentation with no synthetic models or specifications.",
        ),
        public_page_fixture(
            0x102,
            "development/content/products-axial/en",
            "home",
            "products-axial",
            "Axial Development Preview",
            "/en/products/axial",
            "productFamily",
            "Product category",
            "Development category presentation with no synthetic models or specifications.",
        ),
        public_page_fixture(
            0x103,
            "development/content/products-cross-flow/en",
            "home",
            "products-cross-flow",
            "Cross-flow Development Preview",
            "/en/products/cross-flow",
            "productFamily",
            "Product category",
            "Development category presentation with no synthetic models or specifications.",
        ),
        public_page_fixture(
            0x104,
            "development/content/products-inline-duct/en",
            "home",
            "products-inline-duct",
            "Inline Duct Development Preview",
            "/en/products/inline-duct",
            "productFamily",
            "Product category",
            "Development category presentation with no synthetic models or specifications.",
        ),
        public_page_fixture(
            0x105,
            "development/content/products-motors/en",
            "home",
            "products-motors",
            "Motors Development Preview",
            "/en/products/motors",
            "productFamily",
            "Product category",
            "Development category presentation with no synthetic models or specifications.",
        ),
        public_page_fixture(
            0x106,
            "development/content/fan-selector/en",
            "home",
            "fan-selector",
            "Fan Selector Development Preview",
            "/en/products/selector",
            "selector",
            "Product discovery",
            "The client-side selector starts with no validated candidates until published product data is available.",
        ),
        public_page_fixture(
            0x107,
            "development/content/product-compare/en",
            "home",
            "product-compare",
            "Product Compare Development Preview",
            "/en/products/compare",
            "compare",
            "Product discovery",
            "The comparison workspace contains no fixed rows, scores, or synthetic product facts.",
        ),
        public_page_fixture(
            0x110,
            "development/content/solutions-index/en",
            "solution",
            "index",
            "Solutions Development Preview",
            "/en/solutions",
            "solutionIndex",
            "Solutions",
            "Application routes are placeholders and do not establish model suitability.",
        ),
        public_page_fixture(
            0x111,
            "development/content/solution-hvac/en",
            "solution",
            "hvac",
            "HVAC Development Preview",
            "/en/solutions/hvac",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x112,
            "development/content/solution-refrigeration/en",
            "solution",
            "refrigeration",
            "Refrigeration Development Preview",
            "/en/solutions/refrigeration",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x113,
            "development/content/solution-data-centers/en",
            "solution",
            "data-centers",
            "Data Centers Development Preview",
            "/en/solutions/data-centers",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x114,
            "development/content/solution-energy-storage/en",
            "solution",
            "energy-storage",
            "Energy Storage Development Preview",
            "/en/solutions/energy-storage",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x115,
            "development/content/solution-air-purification/en",
            "solution",
            "air-purification",
            "Air Purification Development Preview",
            "/en/solutions/air-purification",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x116,
            "development/content/solution-cleanroom/en",
            "solution",
            "cleanroom",
            "Cleanroom Development Preview",
            "/en/solutions/cleanroom",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x117,
            "development/content/solution-industrial-ventilation/en",
            "solution",
            "industrial-ventilation",
            "Industrial Ventilation Development Preview",
            "/en/solutions/industrial-ventilation",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x118,
            "development/content/solution-commercial-buildings/en",
            "solution",
            "commercial-buildings",
            "Commercial Buildings Development Preview",
            "/en/solutions/commercial-buildings",
            "solutionDetail",
            "Solution route",
            "This placeholder does not assert suitability for any product or operating condition.",
        ),
        public_page_fixture(
            0x120,
            "development/content/technology-index/en",
            "technology",
            "index",
            "Technology Development Preview",
            "/en/technology",
            "technologyIndex",
            "Technology",
            "Technology routes are non-indexable development placeholders pending reviewed evidence.",
        ),
        public_page_fixture(
            0x121,
            "development/content/technology-ec-motor/en",
            "technology",
            "ec-motor",
            "EC Motor Development Preview",
            "/en/technology/ec-motor",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no model-specific motor, control, or performance claim.",
        ),
        public_page_fixture(
            0x122,
            "development/content/technology-aerodynamics/en",
            "technology",
            "aerodynamics",
            "Aerodynamics Development Preview",
            "/en/technology/aerodynamics",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no model-specific aerodynamic or performance claim.",
        ),
        public_page_fixture(
            0x123,
            "development/content/technology-airflow-pressure/en",
            "technology",
            "airflow-and-pressure",
            "Airflow and Pressure Development Preview",
            "/en/technology/airflow-and-pressure",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no operating point, curve, unit conversion, or test claim.",
        ),
        public_page_fixture(
            0x124,
            "development/content/technology-control/en",
            "technology",
            "control",
            "Control Development Preview",
            "/en/technology/control",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no wiring, interface, compatibility, or safety instruction.",
        ),
        public_page_fixture(
            0x125,
            "development/content/technology-efficiency/en",
            "technology",
            "efficiency",
            "Efficiency Development Preview",
            "/en/technology/efficiency",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no efficiency value, saving estimate, or performance claim.",
        ),
        public_page_fixture(
            0x126,
            "development/content/technology-noise-vibration/en",
            "technology",
            "noise-and-vibration",
            "Noise and Vibration Development Preview",
            "/en/technology/noise-and-vibration",
            "technologyDetail",
            "Technology route",
            "This placeholder contains no acoustic value, measurement setup, or product comparison.",
        ),
        public_page_fixture(
            0x130,
            "development/content/articles-index/en",
            "article",
            "index",
            "Articles Development Preview",
            "/en/resources/articles",
            "articleIndex",
            "Resources",
            "The article collection is database-backed and intentionally empty until editorial records are reviewed.",
        ),
        public_page_fixture(
            0x131,
            "development/content/faqs-index/en",
            "faq",
            "index",
            "FAQ Development Preview",
            "/en/resources/faqs",
            "faqIndex",
            "Resources",
            "The FAQ collection is database-backed and contains no invented questions or answers.",
        ),
        public_page_fixture(
            0x132,
            "development/content/case-studies-index/en",
            "caseStudy",
            "index",
            "Case Studies Development Preview",
            "/en/resources/case-studies",
            "caseStudyIndex",
            "Resources",
            "The case-study collection remains empty until evidence and publication permissions are approved.",
        ),
        public_page_fixture(
            0x133,
            "development/content/downloads-index/en",
            "download",
            "index",
            "Downloads Development Preview",
            "/en/resources/downloads",
            "downloadIndex",
            "Resources",
            "The download collection contains no fabricated files, versions, certificates, or model links.",
        ),
        public_page_fixture(
            0x140,
            "development/content/company-about/en",
            "company",
            "about",
            "About Development Preview",
            "/en/company/about",
            "about",
            "Company",
            "This non-indexable placeholder avoids unreviewed company metrics, certifications, and legal claims.",
        ),
        public_page_fixture(
            0x141,
            "development/content/company-contact/en",
            "company",
            "contact",
            "Contact Development Preview",
            "/en/company/contact",
            "contact",
            "Company",
            "This placeholder exercises the Contact form without publishing unconfirmed personal contact details.",
        ),
        public_page_fixture(
            0x150,
            "development/content/rfq-index/en",
            "home",
            "rfq-index",
            "Request a Quote Development Preview",
            "/en/request-a-quote",
            "rfqRouter",
            "RFQ",
            "Choose a structured inquiry path; development fixtures do not imply response times or product suitability.",
        ),
        public_page_fixture(
            0x151,
            "development/content/rfq-product/en",
            "home",
            "rfq-product",
            "Product RFQ Development Preview",
            "/en/request-a-quote/product",
            "rfqForm",
            "RFQ",
            "The form requires a published product context and accepts no public attachment upload.",
        ),
        public_page_fixture(
            0x152,
            "development/content/rfq-selection/en",
            "home",
            "rfq-selection",
            "Selection RFQ Development Preview",
            "/en/request-a-quote/selection",
            "rfqForm",
            "RFQ",
            "The form collects structured selection context without inventing a recommended model.",
        ),
        public_page_fixture(
            0x153,
            "development/content/rfq-project/en",
            "home",
            "rfq-project",
            "Project RFQ Development Preview",
            "/en/request-a-quote/project",
            "rfqForm",
            "RFQ",
            "The form exercises project inquiry fields without making delivery or engineering commitments.",
        ),
        public_page_fixture(
            0x154,
            "development/content/rfq-replacement/en",
            "home",
            "rfq-replacement",
            "Replacement RFQ Development Preview",
            "/en/request-a-quote/replacement",
            "rfqForm",
            "RFQ",
            "The form exercises replacement inquiry fields without asserting compatibility.",
        ),
        public_page_fixture(
            0x160,
            "development/content/search/en",
            "home",
            "search",
            "Search Development Preview",
            "/en/search",
            "search",
            "Search",
            "Search returns only published projections and this route remains non-indexable.",
        ),
        public_page_fixture(
            0x170,
            "development/content/privacy/en",
            "legal",
            "privacy",
            "Privacy Development Preview",
            "/en/privacy",
            "legal",
            "Legal",
            "Development placeholder only; it is not an approved privacy notice.",
        ),
        public_page_fixture(
            0x171,
            "development/content/terms/en",
            "legal",
            "terms",
            "Terms Development Preview",
            "/en/terms",
            "legal",
            "Legal",
            "Development placeholder only; it is not an approved terms document.",
        ),
        public_page_fixture(
            0x172,
            "development/content/cookie-settings/en",
            "legal",
            "cookie-settings",
            "Cookie Settings Development Preview",
            "/en/cookie-settings",
            "legal",
            "Legal",
            "Development placeholder for consent controls; it is not a legal policy.",
        ),
    ];

    if let Some(products) = pages
        .iter_mut()
        .find(|page| page.canonical_path == Some("/en/products"))
    {
        products.page_slots["categories"] = product_category_presentations();
    }
    let categories = [
        ("/en/products/centrifugal", "centrifugal"),
        ("/en/products/axial", "axial"),
        ("/en/products/cross-flow", "crossFlow"),
        ("/en/products/inline-duct", "inlineDuct"),
        ("/en/products/motors", "motors"),
    ];
    for (path, code) in categories {
        if let Some(page) = pages
            .iter_mut()
            .find(|page| page.canonical_path == Some(path))
        {
            page.page_slots["category"] = product_category_presentations()
                .as_array()
                .and_then(|categories| {
                    categories
                        .iter()
                        .find(|category| category["code"].as_str() == Some(code))
                })
                .cloned()
                .unwrap_or(Value::Null);
        }
    }
    pages
}
