[package]
name = "airtek-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
production = ["airtek-runtime/production", "airtek-jobs/production"]
devtools = ["airtek-runtime/devtools", "airtek-jobs/devtools"]

[dependencies]
airtek-runtime.workspace = true
airtek-jobs.workspace = true
dotenvy.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "airtek-worker"
path = "src/main.rs"
