[package]
name = "airtek-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
production = ["airtek-runtime/production", "airtek-http/production"]
devtools = ["airtek-runtime/devtools", "airtek-http/devtools"]

[dependencies]
airtek-runtime.workspace = true
airtek-http.workspace = true
axum.workspace = true
dotenvy.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "airtek-api"
path = "src/main.rs"
